name: 'OSBT Setup Action'
description: 'Setup actions for osbt'
inputs:
  version:
    description: "osbt version"
    required: true
    default: "0.0.1"

runs:
  using: "composite"
  steps:
    - name: setup osbt
      run: |
          cd /tmp
          curl -Lo osbt https://github.com/oidc-scenario-based-tester/osbt/releases/download/v${{ inputs.version }}/osbt_${{ inputs.version }}_linux_amd64
          sudo mv osbt /usr/local/bin/
          sudo chmod +x /usr/local/bin/osbt
          osbt --help
      shell: bash
    - name: run osbt server
      run: osbt server &
      shell: bash
    - name: setup attacker-op
      run: |
          cd /tmp
          curl -Lo attacker-op https://github.com/oidc-scenario-based-tester/attacker-op/releases/download/v${{ inputs.version }}/attacker-op_${{ inputs.version }}_linux_amd64
          sudo mv attacker-op /usr/local/bin/
          sudo chmod +x /usr/local/bin/attacker-op
      shell: bash
    - name: run attacker-op
      run: attacker-op &
      shell: bash
    - name: install mitmproxy
      run: |
          sudo apt-get update
          sudo apt-get install -y mitmproxy
      shell: bash
    - name: setup mitmproxy extension
      run: |
          cd /tmp
          curl -Lo proxy-extension.py https://github.com/oidc-scenario-based-tester/osbt/releases/download/v${{ inputs.version }}/proxy-extension.py
      shell: bash
    - name: run mitmproxy extension
      run: mitmdump -s /tmp/proxy-extension.py &
      shell: bash